Repository hedyorg/hedy, pull requests merged in 2022-12, with the labels that each got.

#3745 [FIX] Added brackets around keywords in adventures in de
  content/adventures/de.yaml
  content/commands/fi.yaml
  tests/test_snippets/test_adventures.py
  tests/test_snippets/test_level_commands.py
Labels: Weblate-lock

#3739 [LANGUAGE] added not in command for list
  content/adventures/es.yaml
  content/keywords/en.yaml
  grammars/keywords-ar.lark
  grammars/keywords-bg.lark
  grammars/keywords-de.lark
  grammars/keywords-en.lark
  grammars/keywords-eo.lark
  grammars/keywords-es.lark
  grammars/keywords-et.lark
  grammars/keywords-fa.lark
  grammars/keywords-fr.lark
  grammars/keywords-he.lark
  grammars/keywords-hi.lark
  grammars/keywords-hu.lark
  grammars/keywords-id.lark
  grammars/keywords-it.lark
  grammars/keywords-ja.lark
  grammars/keywords-nb_NO.lark
  grammars/keywords-nl.lark
  grammars/keywords-pa_PK.lark
  grammars/keywords-pl.lark
  grammars/keywords-pt_BR.lark
  grammars/keywords-pt_PT.lark
  grammars/keywords-ru.lark
  grammars/keywords-sq.lark
  grammars/keywords-sv.lark
  grammars/keywords-sw.lark
  grammars/keywords-template.lark
  grammars/keywords-th.lark
  grammars/keywords-tn.lark
  grammars/keywords-tr.lark
  grammars/keywords-uk.lark
  grammars/keywords-zh_Hans.lark
  grammars/level5-Additions.lark
  hedy.py
  highlighting/highlighting.json
  highlighting/list_keywords.py
  tests/test_level/test_level_05.py
Labels: Weblate-lock, first timer

#3797 [CONTENT] Add `pressed` keyword to cheat sheets
  content/cheatsheets/en.yaml
Labels: content

#3812 [fix] The issue with Quiz level 1 in Dutch is fixed
  content/quizzes/en.yaml
  content/quizzes/nl.yaml
Labels: Weblate-lock

#3810 [CONTENT] Dutch translations of #3259
  content/adventures/en.yaml
  content/adventures/nl.yaml
Labels: Weblate-lock

#3804 [FIX] i escaping and modified tests accordingly - bug #3676
  hedy.py
  tests/Tester.py
  tests/test_level/test_level_02.py
  tests/test_level/test_level_06.py
  tests/test_level/test_level_07.py
  tests/test_level/test_level_09.py
Labels: first timer

#3828 [UI] Add a New Year's adventure to Level 11
  content/adventures/en.yaml
  hedy_content.py
Labels: Weblate-lock

#3864 [FIX] Fixing unit test (level 7)
  hedy.py
  highlighting/rules_list.py
  tests/Tester.py
  tests/test_level/test_level_03.py
  tests/test_level/test_level_04.py
  tests/test_level/test_level_05.py
  tests/test_level/test_level_07.py
  tests/test_level/test_level_08.py
  tests/test_level/test_level_10.py
  tests/test_level/test_level_12.py
  tests/test_level/test_level_16.py
  tests/test_level/test_level_18.py
  tests/test_public_programs/extract-programs.py
  tests/test_public_programs/test_public_programs.py
  tests/test_snippets/test_cheatsheets.py
  tests/test_snippets/test_parsons.py
  tests/test_translation_level/test_translation_level_06.py
  tests_e2e.py
  website/auth_pages.py
Labels: bug, level7

#3871 Parrot adventure level 4
  content/adventures/en.yaml
  content/adventures/nl.yaml
  hedy_content.py
Labels: Weblate-lock

#3880 [CONTENT] fix a few translated keys
  content/adventures/ru.yaml
  content/adventures/tn.yaml
  content/cheatsheets/ar.yaml
Labels: Weblate-lock
