Repository hedyorg/hedy, pull requests merged in 2022-08, with the labels that each got.

#3114 Fix failing translations for hedy exceptions #1804
  .github/workflows/unittests.yml
  messages.pot
  tests/test_translation_error.py
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
  website/auth.py
Labels: Ready, Weblate-block

#3118 Improve program reset on stop
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/vendor.d.ts
Labels: Ready

#3116 [LANGUAGE] Changes Github Workflow to execute deployment script
  .github/workflows/unittests.yml
Labels: Ready

#3126 [BUG FIX] Language switcher dropdown works again
  templates/incl-editor-and-output.html
Labels: Ready

#3117 Translations update from Hosted Weblate
  content/adventures/pl.yaml
  translations/es/LC_MESSAGES/messages.po
Labels: Ready

#3125 [UI FIX] Improves readability of achievements overlay
  static/css/generated.css
  templates/achievements.html
Labels: Ready

#3132 [BUG FIX] Auto selects first tab when intro tab doesn't exist
  static/js/appbundle.js
  static/js/tabs.ts
Labels: Ready

#3123 [FEATURE] Allows teachers to duplicate classes
  messages.pot
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/teachers.ts
  templates/for-teachers.html
  tests_e2e.py
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
  website/teacher.py
Labels: Ready

#3141 [FIX] Catch non-supported languages for Babel
  app.py
  hedy_content.py
Labels: Ready

#3137 [LANGUAGE] Remove punctuation in grammar and class
  grammars/level1.lark
  grammars/level2-Additions.lark
  grammars/level3-Additions.lark
  grammars/level4-Additions.lark
  hedy.py
  tests/test_level/test_level_02.py
  tests/test_level/test_level_03.py
Labels: Ready

#3140 [BUG FIX] Updating of profile works again
  website/auth.py
Labels: Ready

#3139 Adds achievement for duplicating a class
  content/achievements/ar.yaml
  content/achievements/bg.yaml
  content/achievements/bn.yaml
  content/achievements/cs.yaml
  content/achievements/de.yaml
  content/achievements/el.yaml
  content/achievements/en.yaml
  content/achievements/eo.yaml
  content/achievements/es.yaml
  content/achievements/et.yaml
  content/achievements/fa.yaml
  content/achievements/fr.yaml
  content/achievements/fy.yaml
  content/achievements/he.yaml
  content/achievements/hi.yaml
  content/achievements/hu.yaml
  content/achievements/id.yaml
  content/achievements/it.yaml
  content/achievements/ja.yaml
  content/achievements/ko.yaml
  content/achievements/nb_NO.yaml
  content/achievements/nl.yaml
  content/achievements/pl.yaml
  content/achievements/pt_BR.yaml
  content/achievements/pt_PT.yaml
  content/achievements/ru.yaml
  content/achievements/sv.yaml
  content/achievements/sw.yaml
  content/achievements/tr.yaml
  content/achievements/zh_Hans.yaml
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/teachers.ts
  templates/achievements.html
  website/teacher.py
Labels: Ready, Weblate-block

#3143 Update translations of class customizations to improve readability
  translations/en/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
Labels: Ready, Weblate-block

#3148 [FEATURE] Implements report button to enable users to report public programs
  app.py
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
  templates/explore.html
  templates/incl-editor-and-output.html
  website/programs.py
Labels: Ready

#3152 [BUG FIX] Parsons shows correctly when switching from quiz tab
  static/js/appbundle.js
  static/js/tabs.ts
Labels: Ready

#3162 [BUG FIX] Admin functionality to change user mail works again
  templates/admin/admin-users.html
Labels: Ready

#3167 [FIX] disable test requests on Heroku
  utils.py
Labels: Ready

#3150 Translations update from Hosted Weblate
  content/achievements/tn.yaml
  content/adventures/ar.yaml
  content/adventures/de.yaml
  content/adventures/el.yaml
  content/adventures/eo.yaml
  content/adventures/tr.yaml
  content/quizzes/ar.yaml
  translations/eo/LC_MESSAGES/messages.po
Labels: Ready

#3174 [BUG FIX] Fixes styling of reset page
  templates/reset.html
Labels: Ready

#3178 Adds status banner when having a pending teacher request
  messages.pot
  templates/profile.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tn/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Ready

#3185 Attempt 2 for PR public tags
  app.py
  messages.pot
  static/css/generated.css
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/auth.ts
  templates/admin/admin-users.html
  templates/public-page.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tn/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
  website/auth.py
Labels: Ready

#3179 Enables users to request a teacher account after signup
  messages.pot
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/auth.ts
  templates/profile.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tn/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
  website/auth.py
Labels: Ready

#3154 Changes for-teachers page, give manual a dedicated page
  app.py
  messages.pot
  static/js/appbundle.js
  static/js/teachers.ts
  templates/for-teachers.html
  templates/incl-menubar.html
  templates/teacher-manual.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tn/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
  website/teacher.py
Labels: Ready

#3200 Po cleanup
  CONTRIBUTING.md
  messages.pot
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tn/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Weblate-block

#3207 [FEATURE] Enables admin to filter on username
  static/js/app.ts
  static/js/appbundle.js
  templates/admin/admin-users.html
  website/admin.py
Labels: Ready

#3209 Shows profile image in menubar
  app.py
  build-tools/heroku/tailwind/styles.css
  static/css/generated.css
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/auth.ts
  templates/incl-menubar.html
  translations/en/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  website/auth.py
Labels: Ready

#3213 [FEATURE] Enable filtering on submitted programs
  app.py
  build-tools/heroku/tailwind/styles.css
  messages.pot
  static/css/generated.css
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
  templates/programs.html
  translations/en/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
Labels: Ready

#3223 Adds button to create public profile when not created yet
  messages.pot
  static/css/generated.css
  templates/landing-page.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tn/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Ready, Weblate-block

#3218 Fixes main container paddings
  templates/achievements.html
  templates/admin/admin-achievements.html
  templates/admin/admin-adventures.html
  templates/admin/admin-classes.html
  templates/admin/admin-logs.html
  templates/admin/admin-stats.html
  templates/admin/admin-users.html
  templates/auth.html
  templates/class-logs.html
  templates/class-overview.html
  templates/class-prejoin.html
  templates/class-stats.html
  templates/create-accounts.html
  templates/landing-page.html
  templates/learn-more.html
  templates/signup.html
  templates/view-adventure.html
Labels: Ready

#3217 [FEATURE] Enables automatic generating of random passwords on multiple account creation
  messages.pot
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/teachers.ts
  templates/create-accounts.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tn/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Ready

#3226 Adds parsons step to tutorial
  app.py
  content/tutorials/en.yaml
  content/tutorials/nl.yaml
  hedyweb.py
  static/js/appbundle.js
  static/js/tutorial.ts
Labels: Ready

#3233 Capitalizes first letter of username
  templates/highscores.html
  templates/incl-menubar.html
  templates/landing-page.html
  templates/public-page.html
Labels: Ready

#3243 Enables admin to view class overview
  templates/admin/admin-classes.html
  templates/class-overview.html
  templates/customize-class.html
  website/teacher.py
Labels: Ready

#3241 [BUG FIX] Fix not showing of save/share option on corresponding tutorial step
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/tutorials/intro.ts
Labels: Ready

#3247 [BUG FIX] Correctly empty modal prompt on succes
  static/js/appbundle.js
  static/js/modal.ts
Labels: Ready

#3240 [BUG FIX] No longer shows unsaved changes pop-up when switching from parsons tab
  static/js/app.ts
  static/js/appbundle.js
Labels: Ready
