Repository hedyorg/hedy, pull requests merged in 2022-06, with the labels that each got.

#2852 Refactor level 9 tests #2436
  tests/test_level/test_level_08.py
  tests/test_level/test_level_09.py
Labels: Ready

#2889 add regular prefix also when using turtle
  static/js/app.ts
  static/js/appbundle.js
  tests/test_level/test_level_02.py
Labels: Ready

#2885 Makes sure to always generate grammar before starting tests
  build-tools/github/validate-tests
Labels: Ready

#2859 [CHORE] Clean up quiz css
  build-tools/heroku/tailwind/styles.css
  build-tools/heroku/tailwind/tailwind.config.js
  content/quizzes/nl.yaml
  static/css/generated.css
  static/css/progress-bar.css
  static/css/quiz-css.css
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/quiz.ts
  templates/code-page.html
  templates/layout.html
  templates/quiz.html
Labels: Ready

#2892 [FIX] Verify if keyword needs indentation for all languages
  hedy.py
  tests/test_level/test_level_14.py
  tests/test_level/test_level_15.py
Labels: Ready

#2891 [BUG FIX] All filtering options on admin users page work again
  templates/admin/admin-users.html
  utils.py
  website/admin.py
Labels: Ready

#2879 [FEATURE] Enables hiding / showing of parsons through class customizations
  app.py
  hedyweb.py
  messages.pot
  templates/customize-class.html
  templates/incl-adventure-tabs.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Ready

#2856 Remove double example codes
  content/adventures/ar.yaml
  content/adventures/bg.yaml
  content/adventures/bn.yaml
  content/adventures/cs.yaml
  content/adventures/de.yaml
  content/adventures/el.yaml
  content/adventures/en.yaml
  content/adventures/eo.yaml
  content/adventures/es.yaml
  content/adventures/fa.yaml
  content/adventures/fr.yaml
  content/adventures/fy.yaml
  content/adventures/hi.yaml
  content/adventures/hu.yaml
  content/adventures/id.yaml
  content/adventures/it.yaml
  content/adventures/nb_NO.yaml
  content/adventures/nl.yaml
  content/adventures/pl.yaml
  content/adventures/pt_BR.yaml
  content/adventures/pt_PT.yaml
  content/adventures/ru.yaml
  content/adventures/sw.yaml
  content/adventures/tr.yaml
  content/adventures/zh_Hans.yaml
  grammars/keywords-pl.lark
  grammars/level5-Additions.lark
  tests/test_snippets/test_adventures.py
Labels: Weblate-block

#2903 Fixes for text consistency, marked commands and missing examples in Commands
  content/commands/ar.yaml
  content/commands/bg.yaml
  content/commands/bn.yaml
  content/commands/cs.yaml
  content/commands/de.yaml
  content/commands/el.yaml
  content/commands/en.yaml
  content/commands/eo.yaml
  content/commands/es.yaml
  content/commands/et.yaml
  content/commands/fa.yaml
  content/commands/fr.yaml
  content/commands/fy.yaml
  content/commands/hi.yaml
  content/commands/hu.yaml
  content/commands/id.yaml
  content/commands/it.yaml
  content/commands/nb_NO.yaml
  content/commands/nl.yaml
  content/commands/pl.yaml
  content/commands/pt_BR.yaml
  content/commands/pt_PT.yaml
  content/commands/ru.yaml
  content/commands/sw.yaml
  content/commands/tr.yaml
  content/commands/zh_Hans.yaml
Labels: Weblate-block

#2908 Tests for incomplete code
  highlighting/highlighting.json
  highlighting/rules_automaton.py
  static/js/appbundle.js
  static/js/appbundle.js.map
  tests/Highlighter.py
Labels: Ready

#2932 [BUG FIX] Empty code output on switching Parsons exercise
  content/parsons/ar.yaml
  content/parsons/bg.yaml
  content/parsons/bn.yaml
  content/parsons/cs.yaml
  content/parsons/de.yaml
  content/parsons/el.yaml
  content/parsons/en.yaml
  content/parsons/eo.yaml
  content/parsons/es.yaml
  content/parsons/et.yaml
  content/parsons/fa.yaml
  content/parsons/fr.yaml
  content/parsons/fy.yaml
  content/parsons/hi.yaml
  content/parsons/hu.yaml
  content/parsons/id.yaml
  content/parsons/it.yaml
  content/parsons/ja.yaml
  content/parsons/nb_NO.yaml
  content/parsons/pl.yaml
  content/parsons/pt_BR.yaml
  content/parsons/pt_PT.yaml
  content/parsons/ru.yaml
  content/parsons/sw.yaml
  content/parsons/tr.yaml
  content/parsons/zh_Hans.yaml
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/parsons.ts
Labels: Ready

#2933 [BUG FIX] Drag drop parsons works in Firefox
  content/parsons/en.yaml
  templates/incl-editor-and-output.html
Labels: Ready

#2906 [UI IMPROVEMENT] Improve cheatsheet UI
  static/js/app.ts
  templates/cheatsheet.html
Labels: Ready

#2951 All image alt attributes are translatable
  messages.pot
  templates/achievements.html
  templates/base_email.html
  templates/cheatsheet.html
  templates/class-prejoin.html
  templates/error-page.html
  templates/incl-editor-and-output.html
  templates/incl-menubar.html
  templates/landing-page.html
  templates/layout.html
  templates/profile.html
  templates/public-page.html
  templates/quiz.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Ready, Weblate-block

#2950 [BUG FIX] Parsons exercises with indentation work as expected
  content/parsons/en.yaml
  content/parsons/nl.yaml
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
Labels: Ready, Weblate-block

#2957 et Parsons contribution is correctly translated again
  content/parsons/es.yaml
  content/parsons/et.yaml
Labels: Ready, Weblate-block

#2931 [FEATURE] Adds highscores page
  app.py
  messages.pot
  static/css/generated.css
  templates/highscores.html
  templates/incl-menubar.html
  tests_e2e.py
  translations/en/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  website/auth.py
  website/database.py
Labels: Ready, Weblate-block

#2942 files from hedyindafny repo added to hedy repo in a folder
  semantics/Dafny/README.md
  semantics/Dafny/hedy1-properties.dfy
  semantics/Dafny/hedy1-tree.dfy
  semantics/Dafny/hedy1.cs
  semantics/Dafny/hedy1.dfy
  semantics/Dafny/hedy2.cs
  semantics/Dafny/hedy2.dfy
  semantics/Dafny/hedy3.cs
  semantics/Dafny/hedy3.dfy
  semantics/Dafny/hedy4.cs
  semantics/Dafny/hedy4.dfy
  semantics/Dafny/hedy5.cs
  semantics/Dafny/hedy5.dfy
  semantics/Dafny/oldapproachhedy.dfy
  semantics/SEMANTICS.md
Labels: Ready

#2953 Adds option to quiz question to show output container
  build-tools/heroku/tailwind/styles.css
  content/quizzes/en.yaml
  content/quizzes/quizzes.schema.json
  static/css/generated.css
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/quiz.ts
  templates/quiz.html
Labels: Ready, Weblate-block

#2929 [PERFORMANCE] Cache all public programs once on server start
  app.py
  website/database.py
Labels: Ready

#2936 [UI FIX] Improves styling of landing page elements
  build-tools/heroku/tailwind/tailwind.full.js
  static/css/generated.css
  templates/landing-page.html
Labels: Ready

#2976 [BUG FIX] Sharing a program from the programs page now shows correct modal
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
Labels: Ready

#2967 [BUG FIX] Highscores are sorted correctly
  app.py
  website/database.py
Labels: Ready

#2928 [BUG FIX] Allow spaces before lines of code up to level 7, fixes #1142
  grammars/level1.lark
  grammars/level4-Additions.lark
  grammars/level6-Additions.lark
  tests/test_level/test_level_01.py
  tests/test_level/test_level_02.py
  tests/test_level/test_level_04.py
  tests/test_level/test_level_05.py
Labels: Ready

#2971 [CONTENT] Adds highscore intro text
  messages.pot
  templates/highscores.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Ready, Weblate-block

#2966 [UI IMPROVEMENT] Displays country name instead of fixed 'your country' header
  app.py
  hedy_content.py
  templates/highscores.html
Labels: Ready

#2979 [BUG FIX] Programs filtering works again
  app.py
  tests_e2e.py
  website/database.py
Labels: Ready

#2989 Keep DST download button hidden until fix is found
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
Labels: Ready

#2992 [BUG FIX] Class name displayed correctly on class overview page
  templates/class-overview.html
Labels: Ready
