Repository hedyorg/hedy, pull requests merged in 2022-01, with the labels that each got.

#1494 Move meta from IsValid to Filter
  hedy.py
  tests/test_level_04.py
Labels: wip

#1792 New and adapted german translations
  coursedata/level-defaults/de.yaml
  coursedata/texts/de.yaml
Labels: Ready

#1786 [NEW FEATURE] Re-directs username on explore page to public profile
  app.py
  build-tools/heroku/tailwind/styles.css
  coursedata/texts/en.yaml
  coursedata/texts/nl.yaml
  static/css/generated.css
  templates/explore.html
  templates/view-program-page.html
Labels: Ready

#1801 Quizfile indentation
  coursedata/quizzes/en.yaml
  coursedata/quizzes/nl.yaml
  staticr/css/generated.cssr
Labels: bug

#1779 Refactor stats pages and Add log search to the class stats page #1242
  app.py
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/statistics.ts
  templates/admin-stats.html
  templates/class-stats.html
  templates/stats-shared.html
  website/statistics.py
Labels: Ready

#1808 [CLEAN-UP] Implements index key on programs to improve public filtering
  static/js/appbundle.js
  static/js/appbundle.js.map
  website/database.py
Labels: Ready

#1723 [UI IMPROVEMENT] Reduces width of code editor gutter
  static/css/additional.css
  static/css/generated.css
  static/js/appbundle.js
  static/js/appbundle.js.map
Labels: Ready

#1791 [ACHIEVEMENTS] Adds three new achievements
  app.py
  coursedata/achievements/en.yaml
  coursedata/achievements/nl.yaml
  coursedata/pages/achievements/en.yaml
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/auth.ts
  templates/explore.html
  website/auth.py
Labels: Ready

#1769 [UI IMPROVEMENT] Improves UI of pre-join page to align with overall UI
  coursedata/texts/en.yaml
  templates/class-already-joined.html
  templates/class-prejoin.html
  website/teacher.py
Labels: Ready

#1814 Adds types to semantics level 14
  SEMANTICS.md
Labels: Ready

#1764 [FEATURE] Enables invite to class by username
  app.py
  coursedata/texts/en.yaml
  coursedata/texts/nl.yaml
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/teachers.ts
  templates/class-overview.html
  templates/incl-menubar.html
  templates/profile.html
  website/database.py
  website/teacher.py
Labels: Ready

#1806 [BUG FIX] Explore UI stays consistent independent of username or program length
  app.py
  static/css/additional.css
  static/css/generated.css
  static/js/app.ts
  staticr/css/generated.cssr
  templates/explore.html
Labels: Ready

#1816 Adds explanation <= and >= to text level 14
  coursedata/level-defaults/en.yaml
  coursedata/level-defaults/nl.yaml
Labels: Ready

#1828 translate Dutch words in English content to English
  coursedata/adventures/en.yaml
  coursedata/level-defaults/en.yaml
Labels: Ready

#1826 fix quoting in example code in level 5
  coursedata/level-defaults/en.yaml
Labels: Ready

#1824 fix typo "amout" -> "amount"
  coursedata/level-defaults/en.yaml
Labels: Ready

#1833 [BUG FIXES] Fixes faulty re-direct and makes sure achievement always in user view
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/auth.ts
  templates/layout.html
Labels: Ready

#1821 Add input hedy type and forbid any list operations with the input type #1776
  DESIGN.md
  coursedata/texts/en.yaml
  coursedata/texts/nl.yaml
  hedy.py
  tests/Tester.py
  tests/test_level_03.py
  tests/test_level_05.py
  tests/test_level_06.py
  tests/test_level_14.py
  tests/test_level_17.py
Labels: Ready

#1819 Added emojis to the adventure example codes and added a try button in level 1 for printing emojis
  coursedata/adventures/en.yaml
  coursedata/adventures/nl.yaml
  coursedata/level-defaults/en.yaml
  coursedata/level-defaults/nl.yaml
Labels: Ready

#1840 [FEATURE] Enables filtering on programs page
  app.py
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
  templates/programs.html
  website/database.py
Labels: Ready

#1848 replace "Thanks you" by "Thank you"
  coursedata/adventures/de.yaml
  coursedata/adventures/en.yaml
Labels: Ready

#1841 [FEATURE] Enables teacher to reset student password
  coursedata/texts/en.yaml
  coursedata/texts/nl.yaml
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/teachers.ts
  templates/class-overview.html
  website/auth.py
Labels: Ready

#1844 Translate the 'parrot' adventure to German
  coursedata/adventures/de.yaml
Labels: Ready
