Repository hedyorg/hedy, pull requests merged in 2022-05, with the labels that each got.

#2628 Swapped quiz level 10 and 11
  content/quizzes/ar.yaml
  content/quizzes/bg.yaml
  content/quizzes/bn.yaml
  content/quizzes/cs.yaml
  content/quizzes/de.yaml
  content/quizzes/el.yaml
  content/quizzes/en.yaml
  content/quizzes/es.yaml
  content/quizzes/fa.yaml
  content/quizzes/fr.yaml
  content/quizzes/fy.yaml
  content/quizzes/hi.yaml
  content/quizzes/hu.yaml
  content/quizzes/id.yaml
  content/quizzes/it.yaml
  content/quizzes/nb_NO.yaml
  content/quizzes/nl.yaml
  content/quizzes/pl.yaml
  content/quizzes/pt_BR.yaml
  content/quizzes/pt_PT.yaml
  content/quizzes/ru.yaml
  content/quizzes/sw.yaml
  content/quizzes/tr.yaml
  content/quizzes/zh_Hans.yaml
Labels: Weblate-block

#2627 [CHORE] Adds teacher documentation
  TEACHERS.md
Labels: Ready

#2617 [CHORE] Simplifies quiz yaml
  content/quizzes/ar.yaml
  content/quizzes/bg.yaml
  content/quizzes/bn.yaml
  content/quizzes/cs.yaml
  content/quizzes/de.yaml
  content/quizzes/el.yaml
  content/quizzes/en.yaml
  content/quizzes/es.yaml
  content/quizzes/fa.yaml
  content/quizzes/fr.yaml
  content/quizzes/fy.yaml
  content/quizzes/hi.yaml
  content/quizzes/hu.yaml
  content/quizzes/id.yaml
  content/quizzes/it.yaml
  content/quizzes/nb_NO.yaml
  content/quizzes/nl.yaml
  content/quizzes/pl.yaml
  content/quizzes/pt_BR.yaml
  content/quizzes/pt_PT.yaml
  content/quizzes/quizzes.schema.json
  content/quizzes/ru.yaml
  content/quizzes/sw.yaml
  content/quizzes/tr.yaml
  content/quizzes/zh_Hans.yaml
  static/css/generated.css
  templates/quiz/feedback.html
  templates/quiz/quiz-result-overview.html
  templates/quiz/quiz_question.html
  website/quiz.py
Labels: Weblate-block

#2635 [CHORE] Adds tests for all pages in all languages
  tests_e2e.py
Labels: Ready

#2656 [UI IMPROVEMENT] Improves programs user overview
  templates/programs.html
Labels: Ready

#2659 Better error for repeat statements without a inner commands
  content/error-messages.txt
  exceptions.py
  grammars/level7-Additions.lark
  hedy.py
  messages.pot
  tests/test_level/test_level_07.py
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Ready, Weblate-block

#2664 Update arabic keywords grammar file
  grammars/keywords-ar.lark
  tests/test_translation_level/test_translation_level_11.py
Labels: Ready

#2655 [UI IMPROVEMENT] Differentiates between keyword and non-keyword languages on menubar
  app.py
  messages.pot
  static/css/generated.css
  templates/incl-menubar.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Ready

#2665 Translations update from Hosted Weblate
  content/achievements/zh_Hans.yaml
  content/pages/zh_Hans.yaml
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Ready

#2671 Disallow double submission of a correct quiz answer
  templates/quiz/quiz-result-overview.html
  website/quiz.py
Labels: Ready

#2674 [CHORE] Removes runhedy file
  runhedy.py
Labels: Ready

#2694 [CHORE] Removes redundant image attribute from adventures
  content/adventures/adventures.schema.json
  content/adventures/ar.yaml
  content/adventures/bg.yaml
  content/adventures/bn.yaml
  content/adventures/cs.yaml
  content/adventures/de.yaml
  content/adventures/el.yaml
  content/adventures/en.yaml
  content/adventures/es.yaml
  content/adventures/fa.yaml
  content/adventures/fr.yaml
  content/adventures/fy.yaml
  content/adventures/hi.yaml
  content/adventures/hu.yaml
  content/adventures/id.yaml
  content/adventures/it.yaml
  content/adventures/nb_NO.yaml
  content/adventures/nl.yaml
  content/adventures/pl.yaml
  content/adventures/pt_BR.yaml
  content/adventures/pt_PT.yaml
  content/adventures/ru.yaml
  content/adventures/sw.yaml
  content/adventures/tr.yaml
  content/adventures/zh_Hans.yaml
Labels: Weblate-block

#2688 Adds input explanation to level 18 in
  content/adventures/en.yaml
  content/commands/en.yaml
  content/commands/nl.yaml
Labels: Ready, Weblate-block

#2698 Translations update from Hosted Weblate
  content/adventures/zh_Hans.yaml
  content/client-messages/ar.yaml
  content/commands/ar.yaml
  content/keywords/ar.yaml
  content/keywords/fr.yaml
  content/keywords/id.yaml
  content/keywords/it.yaml
  content/keywords/pt_BR.yaml
  content/keywords/zh_Hans.yaml
  content/pages/zh_Hans.yaml
  content/quizzes/ar.yaml
  grammars/keywords-fr.lark
  translations/fr/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
Labels: wip

#2681 Adds news items to En and Nl and De
  content/pages/de.yaml
  content/pages/en.yaml
  content/pages/nl.yaml
Labels: Ready, Weblate-block

#2685 Language specific testing of all snippets
  content/commands/ar.yaml
  content/keywords/ar.yaml
  grammars/keywords-ar.lark
  grammars/keywords-fr.lark
  grammars/keywords-id.lark
  grammars/keywords-zh_Hans.lark
  grammars/level12-Additions.lark
  grammars/level5-Additions.lark
  tests/test_snippets/test_adventures.py
  tests/test_snippets/test_level_commands.py
Labels: Ready

#2701 Remove grammar TODOs in level 17 #1632
  grammars/level1.lark
  grammars/level13-Additions.lark
  grammars/level17-Additions.lark
  hedy.py
  hedy_translation.py
Labels: Ready

#2697 Make sleep command accept variables, expressions and list access
  grammars/level2-Additions.lark
  grammars/level3-Additions.lark
  grammars/level6-Additions.lark
  hedy.py
  tests/Tester.py
  tests/test_level/test_level_02.py
  tests/test_level/test_level_03.py
  tests/test_level/test_level_04.py
  tests/test_level/test_level_06.py
  tests/test_level/test_level_12.py
Labels: Ready

#2737 Updated Translation info
  LANGUAGES.md
  TRANSLATING.md
  image/TRANSLATING/1652368824875.png
  image/TRANSLATING/1652368938016.png
  image/TRANSLATING/1652369040371.png
  image/TRANSLATING/1652369170523.png
  image/TRANSLATING/1652370304289.png
  image/TRANSLATING/1652370483598.png
Labels: Ready

#2700 Refactor tests for levels 7 and 8 #2436
  grammars/level8-Additions.lark
  hedy.py
  tests/test_level/test_level_01.py
  tests/test_level/test_level_06.py
  tests/test_level/test_level_07.py
  tests/test_level/test_level_08.py
  tests/test_level/test_level_09.py
Labels: Ready

#2707 [CLEAN-UP] Created dedicated app route for for-teachers page
  app.py
Labels: Ready

#2727 Typo
  content/adventures/en.yaml
Labels: Ready, Weblate-block

#2723 increasing sorting of translations for syntactic coloring and remove camelCase for snake_case
  highlighting/generate-rules-highlighting.py
  highlighting/highlighting-trad.json
  highlighting/rules_list.py
  static/js/appbundle.js
Labels: Ready

#2714 [BUG FIX] Correctly highlight code snippet example on customize adventure page
  messages.pot
  templates/customize-adventure.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Ready

#2720 [BUG FIX] Fixes incorrect pop-up within tutorial
  highlighting/highlighting-trad.json
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/tutorial.ts
Labels: Ready

#2764 [UI IMPROVEMENT] Flips debug button for RTL languages
  static/css/generated.css
  templates/incl-editor-and-output.html
Labels: rtl

#2743 [FEATURE] Adds admin achievement statistics
  templates/admin/admin-achievements.html
  templates/admin/admin.html
  website/admin.py
Labels: Ready

#2734 [BUG FIX] Always shows newest users first in admin users overview
  website/admin.py
  website/database.py
Labels: Ready

#2710 [FEATURE] Implements "Hedy's choice" to set favorites on /explore page
  app.py
  messages.pot
  static/css/generated.css
  static/js/app.ts
  templates/explore.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
  website/database.py
  website/programs.py
Labels: Ready

#2760 [IMPROVEMENT] Speed up GitHub code validation
  tests/test_snippets/test_adventures.py
Labels: Ready

#2801 [BUG FIX] Fixes incorrect quiz translation for English
  content/quizzes/en.yaml
Labels: Ready

#2808 [BUG FIX] Keywords are always correctly localized on /explore page
  app.py
Labels: Ready

#2805 Adds Discord link to CONTRIBUTING.md
  CONTRIBUTING.md
  TRANSLATING.md
Labels: Ready

#2819 [CHORE] Fixed and improves some minor tutorial bugs
  app.py
  static/js/app.ts
  static/js/appbundle.js
  static/js/tutorial.ts
  templates/level-page.html
  translations/en/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
Labels: Ready

#2810 [UI IMPROVEMENT] Starts turtle at bottom of screen going up
  app.py
  content/adventures/en.yaml
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
  tests/Tester.py
  utils.py
Labels: Ready

#2474 Add test for highlighting
  tests/Highlighter.py
  tests/test_highlighting/test_WEBSITE.py
  tests/test_highlighting/test_affectation.py
  tests/test_highlighting/test_arabic.py
  tests/test_highlighting/test_ask_echo.py
  tests/test_highlighting/test_chinese.py
  tests/test_highlighting/test_comment.py
  tests/test_highlighting/test_for.py
  tests/test_highlighting/test_highlighting_simulation.py
  tests/test_highlighting/test_if_block.py
  tests/test_highlighting/test_if_inline.py
  tests/test_highlighting/test_input.py
  tests/test_highlighting/test_list.py
  tests/test_highlighting/test_print.py
  tests/test_highlighting/test_repeat.py
  tests/test_highlighting/test_sleep.py
  tests/test_highlighting/test_turtle.py
  tests/test_highlighting/test_while.py
Labels: Ready

#2770 [TUTORIAL] Adds speak aloud step
  app.py
  messages.pot
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/tutorial.ts
  templates/incl-editor-and-output.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Ready, Weblate-block
