Repository hedyorg/hedy, pull requests merged in 2022-11, with the labels that each got.

#3530 [CONTENT] Fix 3273 in other languages
  WEBLATE.md
  content/quizzes/ar.yaml
  content/quizzes/bg.yaml
  content/quizzes/bn.yaml
  content/quizzes/cs.yaml
  content/quizzes/de.yaml
  content/quizzes/el.yaml
  content/quizzes/es.yaml
  content/quizzes/fa.yaml
  content/quizzes/fy.yaml
  content/quizzes/hi.yaml
  content/quizzes/hu.yaml
  content/quizzes/id.yaml
  content/quizzes/it.yaml
  content/quizzes/pl.yaml
  content/quizzes/pt_BR.yaml
  content/quizzes/pt_PT.yaml
  content/quizzes/ru.yaml
  content/quizzes/sw.yaml
  content/quizzes/tr.yaml
Labels: Keep-updated, Weblate-lock

#3504 Change ACE search and selection styling
  static/vendor/ext-searchbox.js
  static/vendor/theme-monokai.js
Labels: Ace

#3589 Fixed the variable Prix in FR quiz question
  content/quizzes/fr.yaml
Labels: Weblate-lock, first timer

#3606 [TRANSLATION] Add italian translations for the Parrot (Pappagallo) adventure
  content/adventures/it.yaml
Labels: Weblate-lock, first timer

#3483 [Language Idea] Add pressed for binding keyboard events
  app.py
  content/keywords/en.yaml
  content/keywords/nl.yaml
  grammars/keywords-en.lark
  grammars/keywords-template.lark
  grammars/level1.lark
  grammars/level17-Additions.lark
  grammars/level5-Additions.lark
  grammars/level6-Additions.lark
  grammars/level8-Additions.lark
  hedy.py
  hedy_translation.py
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/hedy.d.ts
  static/js/vendor.d.ts
  static/vendor/pygame_4_skulpt/init.js
  tests/Tester.py
  tests/test_level/test_level_05.py
  tests/test_level/test_level_07.py
  tests/test_level/test_level_08.py
  tests/test_level/test_level_09.py
  tests/test_level/test_level_10.py
  tests/test_level/test_level_11.py
  tests/test_level/test_level_12.py
  tests/test_level/test_level_15.py
  tests/test_level/test_level_16.py
  tests/test_level/test_level_17.py
Labels: language

#3628 [CONTENT] #3259 reorder adventures based on difficulty
  content/adventures/en.yaml
  hedy_content.py
Labels: Weblate-lock

#3648 [FIX, CONTENT] Update level 11 quiz
  content/quizzes/ar.yaml
  content/quizzes/bg.yaml
  content/quizzes/bn.yaml
  content/quizzes/cs.yaml
  content/quizzes/de.yaml
  content/quizzes/el.yaml
  content/quizzes/eo.yaml
  content/quizzes/es.yaml
  content/quizzes/et.yaml
  content/quizzes/fa.yaml
  content/quizzes/fr.yaml
  content/quizzes/fy.yaml
  content/quizzes/he.yaml
  content/quizzes/hi.yaml
  content/quizzes/hu.yaml
  content/quizzes/id.yaml
  content/quizzes/it.yaml
  content/quizzes/ja.yaml
  content/quizzes/ko.yaml
  content/quizzes/nb_NO.yaml
  content/quizzes/nl.yaml
  content/quizzes/pa_PK.yaml
  content/quizzes/pl.yaml
  content/quizzes/pt_BR.yaml
  content/quizzes/ru.yaml
  content/quizzes/sq.yaml
  content/quizzes/sv.yaml
  content/quizzes/sw.yaml
  content/quizzes/th.yaml
  content/quizzes/tn.yaml
  content/quizzes/tr.yaml
  content/quizzes/uk.yaml
  content/quizzes/ur.yaml
Labels: Weblate-lock

#3627 [TESTING, CYPRESS] 3624 tests for logs and class statistics button in class page
  templates/class-overview.html
  templates/for-teachers.html
  tests/cypress.config.js
  tests/cypress/e2e/teacher_page/class_page/logs_button.cy.js
  tests/cypress/e2e/teacher_page/class_page/statistics_button.cy.js
  tests/cypress/e2e/tools/classes/class.js
Labels: first timer

#3672 [TESTING, CYPRESS] 3563 tests for the teacher features in the customize class page
  templates/class-overview.html
  tests/cypress.config.js
  tests/cypress/e2e/teacher_page/customize_class_page/ind_adv_button.cy.js
  tests/cypress/e2e/teacher_page/customize_class_page/opening_dates.cy.js
  tests/cypress/e2e/teacher_page/customize_class_page/quiz_score.cy.js
  tests/cypress/e2e/teacher_page/customize_class_page/test_checkboxes.cy.js
  tests/cypress/e2e/tools/classes/class.js
Labels: first timer

#3697 [REFACTORING] Change Parsons YAML structure for code lines
  content/parsons/en.yaml
  content/parsons/nl.yaml
  content/parsons/parsons.schema.json
  hedy_content.py
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/parsons.ts
Labels: Weblate-lock

#3714 [UI] Add syntax highlighting for new 'pressed' keyword (3547)
  highlighting/definition.py
  highlighting/list_keywords.py
  highlighting/rules_list.py
  static/vendor/theme-monokai.js
  tests/Highlighter.py
  tests/test_highlighting/test_if_pressed.py
Labels: syntax-highlighting
