Repository hedyorg/hedy, pull requests merged in 2022-09, with the labels that each got.

#3251 [BUG FIX] Fixes blur button overlay with scrollbar
  templates/incl-editor-and-output.html
Labels: Ready

#3252 [FIX] Hide submitted programs from /explore and public-profile page
  website/database.py
Labels: Ready

#3253 fix: add 'epoch' field to users
  website/database.py
Labels: Keep-updated

#3256 [BUGFIX] Correctly store programming experience
  templates/signup.html
Labels: Keep-updated

#3343 [FIX] Removes print margin line for ace editor
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
Labels: Keep-updated

#3351 Fixed some mistakes in the level 8 quiz
  content/quizzes/en.yaml
  content/quizzes/nl.yaml
Labels: Keep-updated, Weblate-lock

#3332 Enable the turtle commands in all levels
  grammars/level11-Additions.lark
  hedy.py
  messages.pot
  tests/Tester.py
  tests/test_level/test_level_01.py
  tests/test_level/test_level_02.py
  tests/test_level/test_level_03.py
  tests/test_level/test_level_04.py
  tests/test_level/test_level_08.py
  tests/test_level/test_level_12.py
  tests/test_level/test_level_16.py
  tests/test_translation_level/test_translation_level_01.py
  translations/ar/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/tn/LC_MESSAGES/messages.po
  translations/ur/LC_MESSAGES/messages.po
Labels: Weblate-lock

#3334 [LANGUAGE] Simpler way to do 3331
  grammars/level6-Additions.lark
  hedy.py
  tests/test_level/test_level_06.py
  tests/test_level/test_level_12.py
Labels: Keep-updated

#3242 Adds 'start tutorial' button if a tutorial exists for the current lang / level combination
  app.py
  content/tutorials/en.yaml
  hedy_content.py
  hedyweb.py
  messages.pot
  static/js/tutorials/level1.ts
  templates/code-page.html
  templates/layout.html
  templates/level-page.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
Labels: Keep-updated
