Repository hedyorg/hedy, pull requests merged in 2022-10, with the labels that each got.

#3366 Sort research papers by year in descending order
  hedy_content.py
Labels: hacktoberfest-accepted

#3408 3400 content remove red text in adventure mode
  messages.pot
  templates/incl-adventure-tabs.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tn/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/ur/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Keep-updated, Weblate-lock

#3398 [FEATURE] Changes drawing arrow into turtle
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
  utils.py
Labels: Keep-updated

#3405 [UI] Make error grey for better readability
  build-tools/heroku/tailwind/styles.css
  static/css/generated.css
Labels: Keep-updated

#3395 3335 UI idea extend skulpt with pygame4skulpt
  static/js/app.ts
  static/js/appbundle.js
  static/js/hedy.d.ts
  static/js/vendor.d.ts
  static/vendor/pygame_4_skulpt/display.js
  static/vendor/pygame_4_skulpt/draw.js
  static/vendor/pygame_4_skulpt/event.js
  static/vendor/pygame_4_skulpt/font.js
  static/vendor/pygame_4_skulpt/image.js
  static/vendor/pygame_4_skulpt/init.js
  static/vendor/pygame_4_skulpt/key.js
  static/vendor/pygame_4_skulpt/locals.js
  static/vendor/pygame_4_skulpt/mouse.js
  static/vendor/pygame_4_skulpt/time.js
  static/vendor/pygame_4_skulpt/transform.js
  static/vendor/pygame_4_skulpt/version.js
Labels: Keep-updated

#3419 Fixes highlighting of turtle commands from level 11 onwards
  highlighting/highlighting.json
  highlighting/list_keywords.py
  static/js/appbundle.js
  static/js/appbundle.js.map
Labels: Keep-updated

#3457 Some additional french translations
  translations/fr/LC_MESSAGES/messages.po
Labels: Keep-updated

#3426 [BUGFIX] Dissabling autocomplete for changing password
  templates/profile.html
  tests_e2e.py
  website/auth_pages.py
Labels: Keep-updated

#3359 [TURTLE] Generate dst and png files for machines
  app.py
  static/js/app.ts
  static/js/appbundle.js
  templates/incl-editor-and-output.html
Labels: Keep-updated

#3399 [BUG FIX] 'error or empty' achievement can be achieved again
  static/js/app.ts
  templates/layout.html
  website/achievements.py
Labels: Keep-updated

#3442 Slightly adjust and add to swedish translations
  content/adventures/sv.yaml
Labels: Keep-updated

#3438 Changes book titles
  content/quizzes/ar.yaml
  content/quizzes/bg.yaml
  content/quizzes/bn.yaml
  content/quizzes/cs.yaml
  content/quizzes/de.yaml
  content/quizzes/el.yaml
  content/quizzes/en.yaml
  content/quizzes/eo.yaml
  content/quizzes/es.yaml
  content/quizzes/et.yaml
  content/quizzes/fa.yaml
  content/quizzes/fr.yaml
  content/quizzes/fy.yaml
  content/quizzes/he.yaml
  content/quizzes/hi.yaml
  content/quizzes/hu.yaml
  content/quizzes/id.yaml
  content/quizzes/it.yaml
  content/quizzes/ja.yaml
  content/quizzes/ko.yaml
  content/quizzes/nl.yaml
  content/quizzes/pl.yaml
  content/quizzes/pt_BR.yaml
  content/quizzes/pt_PT.yaml
  content/quizzes/ru.yaml
  content/quizzes/sv.yaml
  content/quizzes/sw.yaml
  content/quizzes/tn.yaml
  content/quizzes/tr.yaml
  content/quizzes/ur.yaml
  content/quizzes/zh_Hans.yaml
Labels: Keep-updated, Weblate-lock

#3466 Fixes minor mistakes in quiz level 10
  content/quizzes/nl.yaml
Labels: Keep-updated, Weblate-lock

#3445 [CONTENT] Better explanation for level 18
  content/adventures/en.yaml
  content/adventures/nl.yaml
Labels: Keep-updated, Weblate-lock

#3440 [UI] Add searching to the ACE editor
  static/vendor/ext-searchbox.js
Labels: Keep-updated, Ace

#3420 [UI] Adds Hedy Certificate of Completion
  app.py
  content/achievements/en.yaml
  messages.pot
  templates/certificate.html
  templates/landing-page.html
  templates/public-page.html
  templates/quiz.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tn/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/ur/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
  website/database.py
  website/quiz.py
Labels: Weblate-lock

#3423 [Language] Adds rule for lonely quoted text
  content/error-messages.txt
  exceptions.py
  grammars/level4-Additions.lark
  grammars/level6-Additions.lark
  hedy.py
  messages.pot
  tests/test_level/test_level_04.py
  tests/test_level/test_level_07.py
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tn/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/ur/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Weblate-lock

#3410 Introduce automated checks for PEP8-compliance using flake8
  .github/workflows/flake8-linting.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  setup.cfg
Labels: Keep-updated

#3486 [FIX] Python requirements no longer install on Windows
  requirements.txt
Labels: Keep-updated

#3481 [Language] Allows floats and expressions with turtle
  grammars/level6-Additions.lark
  hedy.py
  tests/Tester.py
  tests/test_level/test_level_01.py
  tests/test_level/test_level_02.py
  tests/test_level/test_level_03.py
  tests/test_level/test_level_04.py
  tests/test_level/test_level_05.py
  tests/test_level/test_level_06.py
  tests/test_level/test_level_07.py
  tests/test_level/test_level_08.py
  tests/test_level/test_level_12.py
  tests/test_level/test_level_16.py
Labels: Keep-updated

#3484 [FIX] Grab translation of turn before error
  app.py
  hedy.py
  hedy_translation.py
Labels: Keep-updated

#3495 [BUG FIX] Admin is able to set user tags again
  website/admin.py
Labels: Keep-updated

#3491 Some image trimming (Issue #3487)
  static/images/Hedy-logo-96x96.png
  static/images/achievement-320x320.png
  static/images/header-3072x500.jpg
  static/images/header.jpg
  templates/incl-menubar.html
  templates/layout.html
  templates/main-page.html
Labels: Keep-updated

#3497 Normalize paths and replace instead of rename to make atomic files work in Windows.
  tests/Highlighter.py
  tests/tests_z_yamlfile.py
  utils.py
Labels: Keep-updated
