Repository hedyorg/hedy, pull requests merged in 2022-07, with the labels that each got.

#3011 Adds new exception to catch repeats with missing parts
  content/error-messages.txt
  exceptions.py
  grammars/level7-Additions.lark
  hedy.py
  messages.pot
  tests/test_level/test_level_07.py
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Weblate-block

#3010 Fixed Babel update command to stop fuzzy matching and prevent translation confusion
  CONTRIBUTING.md
Labels: Ready

#3008 [FIX] Fixes incorrect parsons title translation
  build-tools/heroku/tailwind/styles.css
  messages.pot
  static/css/generated.css
  templates/incl-adventure-tabs.html
  translations/ar/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
Labels: Ready, Weblate-block

#2993 [UI IMPROVEMENT] Improve responsiveness of menubar
  build-tools/heroku/tailwind/styles.css
  static/css/generated.css
  templates/incl-menubar.html
Labels: Ready

#3026 [VALIDATION] Improved mail sending process error handling
  messages.pot
  translations/en/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  website/auth.py
Labels: Ready, Weblate-block

#3025 [UI IMPROVEMENT] Improves admin views
  templates/admin/admin-achievements.html
  templates/admin/admin-adventures.html
  templates/admin/admin-classes.html
  templates/admin/admin-logs.html
  templates/admin/admin-stats.html
  templates/admin/admin-users.html
  website/admin.py
Labels: Ready

#2999 [CHORE] Templates clean-up
  build-tools/heroku/tailwind/styles.css
  build-tools/heroku/tailwind/tailwind.config.js
  static/css/generated.css
  templates/auth.html
  templates/learn-more.html
  templates/login.html
  templates/main-page.html
  templates/recover.html
  templates/reset.html
  templates/signup.html
Labels: Ready

#3028 [BUG FIX] Country correctly removed from highscores when removed from profile
  website/auth.py
Labels: Ready

#3018 Removes email validation field on sign-up
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/auth.ts
  templates/signup.html
  tests_e2e.py
  website/auth.py
Labels: Ready

#3034 Adds a preprocessor step in the grammar merger
  grammars/level17-Additions.lark
  hedy.py
Labels: Ready

#3029 [IMPROVEMENT] Only show variables in variable view that have an actual value
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
Labels: Ready

#3033 Highlight firsts levels
  highlighting/highlighting.json
  highlighting/rules_automaton.py
  static/js/appbundle.js
  tests/Highlighter.py
  tests/test_highlighting/test_WEBSITE.py
  tests/test_highlighting/test_list.py
Labels: Ready

#3046 Highlight level 4
  highlighting/generate-rules-highlighting.py
  highlighting/highlighting.json
  highlighting/list_keywords.py
  highlighting/rules_automaton.py
  static/js/appbundle.js
  static/js/appbundle.js.map
  tests/test_highlighting/test_affectation.py
  tests/test_highlighting/test_list.py
Labels: Ready

#3043 Update to level 11 whats next
  content/adventures/en.yaml
Labels: Ready

#3040 [PERFORMANCE] Makes dropdown menu touch friendly
  build-tools/heroku/tailwind/styles.css
  static/css/generated.css
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
  templates/incl-menubar.html
  templates/level-page.html
Labels: Ready

#3059 [CONTENT FIX] Fixed invalid placeholder in nl level-defaults
  content/adventures/nl.yaml
Labels: Weblate-block

#3066 Enable dynamic keywords for teacher adventures
  app.py
  content/adventures/he.yaml
  hedy_content.py
  messages.pot
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/teachers.ts
  templates/customize-adventure.html
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
  website/teacher.py
Labels: Weblate-block

#3067 Fusion variables in highlighting
  highlighting/list_keywords.py
  highlighting/rules_list.py
Labels: Ready

#3085 [BUG FIX] Keyword placeholders are no longer overwritten at the moment of adventure saving
  website/teacher.py
Labels: Ready

#3089 Refactor tests for level 10 and 11 #2436
  tests/test_level/test_level_08.py
  tests/test_level/test_level_10.py
  tests/test_level/test_level_11.py
Labels: Ready

#3031 [UI IMPROVEMENT] Makes error line highlighting more readable
  build-tools/heroku/tailwind/styles.css
  static/css/additional.css
  static/css/generated.css
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
Labels: Ready

#3092 rename due to the addition of the color command
  content/adventures/en.yaml
  tests/test_highlighting/test_WEBSITE.py
Labels: Ready, Weblate-block

#3087 [FEATURE] Enables teachers to directly add adventures to classes
  messages.pot
  static/css/generated.css
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/teachers.ts
  templates/customize-adventure.html
  templates/customize-class.html
  tests_e2e.py
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
  website/database.py
  website/teacher.py
Labels: Ready, Weblate-block

#3074 [FEATURE] Show amount of pending messages on menu dropdown menu
  app.py
  templates/incl-menubar.html
  templates/profile.html
  website/auth.py
  website/teacher.py
Labels: Ready

#3091 [BUG FIX] Still reload or redirect when closing the achievement pop-up manually
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
  templates/layout.html
Labels: Ready

#3098 [UI FIX] Fixes some minor UI bugs on for-teachers page
  templates/for-teachers.html
Labels: Ready

#3112 [BUGFIX] Fixes list access using indices on level 5+
  hedy.py
  tests/test_level/test_level_05.py
Labels: Ready

#3107 add translation of comma
  highlighting/definition.py
  highlighting/generate-rules-highlighting.py
  highlighting/highlighting-trad.json
  highlighting/highlighting.json
  highlighting/list_keywords.py
  highlighting/rules_automaton.py
  highlighting/rules_list.py
  static/js/appbundle.js
  static/js/appbundle.js.map
  tests/test_highlighting/test_arabic.py
Labels: Ready
