Repository hedyorg/hedy, pull requests merged in 2022-04, with the labels that each got.

#2379 fix quiz level 7
  coursedata/quizzes/nl.yaml
Labels: Ready, Weblate-block

#2395 Example codes clean up nl
  coursedata/adventures/nl.yaml
  coursedata/level-defaults/en.yaml
  coursedata/level-defaults/nl.yaml
Labels: Ready, Weblate-block

#2382 Adds clarifying comment to Rock - Level 9
  coursedata/adventures/en.yaml
Labels: Ready, Weblate-block

#2349 Update the translation for Indonesian keywords
  build-tools/heroku/generate-localized-highlighting.py
  coursedata/keywords/id.yaml
  grammars/keywords-id.lark
  static/js/appbundle.js
  static/js/syntaxLang-id.ts
  static/js/syntaxModesRules.ts
Labels: Ready, Weblate-block

#2378 Add support for inner quotes in text values up until level 12
  grammars/level12-Additions.lark
  hedy.py
  tests/test_level/test_level_02.py
  tests/test_level/test_level_03.py
  tests/test_level/test_level_04.py
  tests/test_level/test_level_05.py
  tests/test_level/test_level_06.py
  tests/test_level/test_level_07.py
  tests/test_level/test_level_08.py
  tests/test_level/test_level_12.py
Labels: Ready

#2363 [BUGFIX] Allow spaces after square brackets and braces
  grammars/level1.lark
  grammars/level14-Additions.lark
  grammars/level18-Additions.lark
  tests/test_level/test_level_16.py
Labels: Ready

#2413 Adds spaces to the keywords definitions and removes them from the grammar
  grammars/keywords-ar.lark
  grammars/keywords-en.lark
  grammars/keywords-es.lark
  grammars/keywords-fr.lark
  grammars/keywords-hi.lark
  grammars/keywords-id.lark
  grammars/keywords-nb_NO.lark
  grammars/keywords-nl.lark
  grammars/keywords-tr.lark
  grammars/level1.lark
  grammars/level10-Additions.lark
  grammars/level11-Additions.lark
  grammars/level12-Additions.lark
  grammars/level13-Additions.lark
  grammars/level14-Additions.lark
  grammars/level15-Additions.lark
  grammars/level16-Additions.lark
  grammars/level17-Additions.lark
  grammars/level18-Additions.lark
  grammars/level2-Additions.lark
  grammars/level3-Additions.lark
  grammars/level4-Additions.lark
  grammars/level5-Additions.lark
  grammars/level6-Additions.lark
  grammars/level7-Additions.lark
  grammars/level8-Additions.lark
  tests/test_level/test_level_01.py
  tests/test_level/test_level_02.py
  tests/test_level/test_level_03.py
  tests/test_level/test_level_04.py
  tests/test_level/test_level_05.py
Labels: Ready

#2423 [BUG FIX] Cheatsheets work again
  app.py
  hedy_content.py
  templates/cheatsheet.html
  tests_e2e.py
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Ready

#2414 [FIX] Only highlighting username on program view page when public profile
  app.py
  templates/view-program-page.html
Labels: Ready

#2426 fixed indentation lvl 15 rock and lvl 3 restaurant NL
  content/adventures/nl.yaml
Labels: Weblate-block

#2416 [CLEAN-UP] Removes fixed error strings, adds dynamic country selector
  app.py
  hedy_content.py
  requirements.txt
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/auth.ts
  templates/profile.html
  templates/signup.html
  website/auth.py
Labels: Ready

#2440 Add support for inner quotes for levels 12 an up #2186
  app.py
  content/error-messages.txt
  exceptions.py
  hedy.py
  tests/test_level/test_level_04.py
  tests/test_level/test_level_12.py
  tests/test_level/test_level_13.py
  tests/test_level/test_level_14.py
  tests/test_level/test_level_15.py
  tests/test_level/test_level_16.py
  tests/test_level/test_level_17.py
  tests/test_level/test_level_18.py
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Ready

#2429 remove space after commands
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/syntaxModesRules.ts
Labels: Ready

#2461 Refactor tests for level 1 and 2 #2436
  content/error-messages.txt
  exceptions.py
  hedy.py
  tests/Tester.py
  tests/test_level/test_level_01.py
  tests/test_level/test_level_02.py
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: Ready

#2446 fix 2442
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/syntaxModesRules.ts
Labels: Ready

#2454 [BUG FIX] Correctly catch invalid levels in url
  app.py
Labels: Ready

#2396 Change creation of ALL_LANGUAGES and rtol/ltor setting to dynamic.
  app.py
  hedy_content.py
  templates/incl-menubar.html
Labels: Ready

#2443 [IMPROVEMENT] Always dynamically parse keywords on /explore and program view
  app.py
  templates/explore.html
  templates/incl-editor-and-output.html
  templates/view-program-page.html
Labels: Ready

#2475 I have corrected grammatical and spelling mistakes in the English Translation file.
  translations/en/LC_MESSAGES/messages.po
Labels: Weblate-block

#2466 Quiz update
  content/quizzes/en.yaml
  content/quizzes/nl.yaml
Labels: Weblate-block

#2465 Adding Colors in Turtle
  content/keywords/en.yaml
  content/keywords/nl.yaml
  grammars/keywords-ar.lark
  grammars/keywords-en.lark
  grammars/keywords-es.lark
  grammars/keywords-fr.lark
  grammars/keywords-hi.lark
  grammars/keywords-id.lark
  grammars/keywords-nb_NO.lark
  grammars/keywords-nl.lark
  grammars/keywords-tr.lark
  grammars/level1.lark
  hedy.py
  hedy_translation.py
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/syntaxLang-ar.ts
  static/js/syntaxLang-en.ts
  static/js/syntaxLang-es.ts
  static/js/syntaxLang-fr.ts
  static/js/syntaxLang-hi.ts
  static/js/syntaxLang-id.ts
  static/js/syntaxLang-nb_NO.ts
  static/js/syntaxLang-nl.ts
  static/js/syntaxLang-template.ts
  static/js/syntaxLang-tr.ts
  static/js/syntaxModesRules.ts
  tests/test_level/test_level_01.py
Labels: Weblate-block

#2496 [SYNTAX HIGHLIGHTER] Small error corrections
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/syntaxModesRules.ts
Labels: Ready

#2503 [UI IMPROVEMENT] Removes copy button from teacher adventure view
  website/teacher.py
Labels: Ready

#2479 [CLEAN-UP] Replaces mail YAMLs with gettext
  content/emails/ar.yaml
  content/emails/bg.yaml
  content/emails/bn.yaml
  content/emails/cs.yaml
  content/emails/de.yaml
  content/emails/el.yaml
  content/emails/en.yaml
  content/emails/es.yaml
  content/emails/fa.yaml
  content/emails/fr.yaml
  content/emails/fy.yaml
  content/emails/hi.yaml
  content/emails/hu.yaml
  content/emails/id.yaml
  content/emails/it.yaml
  content/emails/nb_NO.yaml
  content/emails/nl.yaml
  content/emails/pl.yaml
  content/emails/pt_BR.yaml
  content/emails/pt_PT.yaml
  content/emails/ru.yaml
  content/emails/sw.yaml
  content/emails/tr.yaml
  content/emails/zh_Hans.yaml
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
  website/auth.py
Labels: Weblate-block

#2136 [FEATURE] Localized quiz keywords
  app.py
  build-tools/github/validate-e2e
  content/quizzes/en.yaml
  content/quizzes/nl.yaml
  hedy_content.py
  website/quiz.py
Labels: Ready

#2514 Disallow nested if-statements in levels 5-7 #2339
  grammars/level5-Additions.lark
  grammars/level6-Additions.lark
  grammars/level7-Additions.lark
  grammars/level8-Additions.lark
  hedy.py
  tests/test_level/test_level_05.py
  tests/test_level/test_level_06.py
Labels: Ready

#2533 cleanup unmaintained adventures
  content/adventures/hu.yaml
  content/adventures/id.yaml
Labels: Weblate-block

#2512 Refactor level 3 tests #2436
  hedy.py
  tests/test_level/test_level_01.py
  tests/test_level/test_level_02.py
  tests/test_level/test_level_03.py
  tests/test_level/test_level_04.py
  tests/test_level/test_level_12.py
  tests/test_level/test_level_16.py
Labels: Ready

#2513 [BUG FIX] Fixes common mistakes for nl and nb_NO translations
  app.py
  content/pages/for-teachers/en.yaml
  content/pages/for-teachers/nb_NO.yaml
  content/pages/for-teachers/nl.yaml
Labels: Weblate-block

#2535 #2473 small fixes in NL adventures
  content/adventures/nl.yaml
Labels: Weblate-block

#2548 Refactored tests for level 4 #2436
  hedy.py
  hedy_translation.py
  tests/test_level/test_level_02.py
  tests/test_level/test_level_03.py
  tests/test_level/test_level_04.py
Labels: Ready

#2545 Fix incorrect parsing of ask in level 6 #2497
  grammars/level6-Additions.lark
  tests/test_level/test_level_06.py
Labels: Ready

#2582 Fix typos in en.yaml
  content/adventures/en.yaml
Labels: Weblate-block

#2555 Refactor tests for level 5 and 6 #2436
  tests/Tester.py
  tests/test_level/test_level_04.py
  tests/test_level/test_level_05.py
  tests/test_level/test_level_06.py
Labels: Ready

#2538 [PERFORMANCE] Caches quizzes on server start
  app.py
  content/quizzes/nl.yaml
  hedy_content.py
  hedyweb.py
  templates/incl-adventure-tabs.html
  website/quiz.py
Labels: Ready

#2523 [IMPROVEMENT] Sorts explore programs from new to old
  website/database.py
Labels: Ready

#2585 [FIX] Specifies sort key on public programs
  website/database.py
Labels: Ready

#2557 Improves program time-out handling
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
Labels: Ready

#2507 #2392 fix hard coded text french level 4
  content/adventures/fr.yaml
Labels: Ready, Weblate-block

#2587 [BUG FIX] Quiz level 5 question 1 nl correctly renders again
  content/quizzes/nl.yaml
Labels: Ready, Weblate-block

#2472 Quiz EN new content level 8 and 9
  content/quizzes/en.yaml
  content/quizzes/nl.yaml
Labels: Ready, Weblate-block

#2591 [FEATURE] Implements stop button
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
  static/js/vendor.d.ts
  templates/incl-editor-and-output.html
Labels: Ready

#2604 [IMPROVE] Always set keyword lang to user lang if not specified in profile
  app.py
  content/commands/ar.yaml
  hedy_content.py
  website/auth.py
Labels: Ready

#2572 Adds repeat keyword to levels 11+
  grammars/level11-Additions.lark
  hedy.py
  static/js/syntaxModesRules.ts
  tests/test_level/test_level_11.py
Labels: Ready

#2613 [BUG FIX] Correctly hides stop button on timeout
  static/js/app.ts
  static/js/appbundle.js
  static/js/appbundle.js.map
Labels: Ready

#2615 Adds de, pl, zh_Hans
  content/commands/zh_Hans.yaml
  content/transform_keywords_to_grammar.py
  content/yaml_transformer.py
  grammars/keywords-de.lark
  grammars/keywords-pl.lark
  grammars/keywords-zh_Hans.lark
  grammars/level1.lark
  grammars/level3-Additions.lark
  grammars/level4-Additions.lark
  grammars/level5-Additions.lark
  grammars/level6-Additions.lark
  tests/test_snippets/test_adventures.py
  tests/test_snippets/test_level_commands.py
Labels: Weblate-block
