Repository hedyorg/hedy, pull requests merged in 2024-03, with the labels that each got.

#5195 📜 Content Cleanup upto level 8
  content/adventures/ar.yaml
  content/adventures/bg.yaml
  content/adventures/bn.yaml
  content/adventures/ca.yaml
  content/adventures/cs.yaml
  content/adventures/cy.yaml
  content/adventures/da.yaml
  content/adventures/de.yaml
  content/adventures/el.yaml
  content/adventures/en.yaml
  content/adventures/eo.yaml
  content/adventures/es.yaml
  content/adventures/et.yaml
  content/adventures/fa.yaml
  content/adventures/fi.yaml
  content/adventures/fr.yaml
  content/adventures/fy.yaml
  content/adventures/he.yaml
  content/adventures/hi.yaml
  content/adventures/hu.yaml
  content/adventures/ia.yaml
  content/adventures/id.yaml
  content/adventures/it.yaml
  content/adventures/ja.yaml
  content/adventures/kmr.yaml
  content/adventures/ko.yaml
  content/adventures/mi.yaml
  content/adventures/nb_NO.yaml
  content/adventures/nl.yaml
  content/adventures/pa_PK.yaml
  content/adventures/pap.yaml
  content/adventures/pl.yaml
  content/adventures/pt_BR.yaml
  content/adventures/pt_PT.yaml
  content/adventures/ro.yaml
  content/adventures/ru.yaml
  content/adventures/sq.yaml
  content/adventures/sr.yaml
  content/adventures/sv.yaml
  content/adventures/sw.yaml
  content/adventures/te.yaml
  content/adventures/th.yaml
  content/adventures/tl.yaml
  content/adventures/tn.yaml
  content/adventures/tr.yaml
  content/adventures/uk.yaml
  content/adventures/ur.yaml
  content/adventures/vi.yaml
  content/adventures/zh_Hans.yaml
  content/adventures/zh_Hant.yaml
Labels: Weblate-lock

#5162 🪲Only show programs that has been modified in Overview of programs per adventure
  website/statistics.py
Labels: under-review

#5049 📜Micro-bit code
  Micro-bit/Micro-bit.py
  Micro-bit/hex-converter.py
  Micro-bit/micropython.hex
  hedy.py
  requirements.txt
  tests/Tester.py
  tests/test_level/test_level_01.py
  tests/test_level/test_level_04.py
  tests/test_level/test_level_12.py
  tests/test_snippets/tests/test_level/test_level_02.py
Labels: under-review

#5156 💻 hide all quizes/parsons and show tabs in levels
  app.py
  hedy_content.py
  messages.pot
  templates/customize-class.html
  templates/customize-class/partial-sortable-adventures.html
  tests/cypress/e2e/for-teacher_page/customize_class_page/customize_class.cy.js
  tests/cypress/e2e/for-teacher_page/customize_class_page/customize_class_second_teacher.cy.js
  tests/cypress/e2e/for-teacher_page/customize_class_page/quiz_parsons.cy.js
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/ca/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/cy/LC_MESSAGES/messages.po
  translations/da/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fi/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/ia/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/kmr/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/mi/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pa_PK/LC_MESSAGES/messages.po
  translations/pap/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ro/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sq/LC_MESSAGES/messages.po
  translations/sr/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/te/LC_MESSAGES/messages.po
  translations/th/LC_MESSAGES/messages.po
  translations/tl/LC_MESSAGES/messages.po
  translations/tn/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/uk/LC_MESSAGES/messages.po
  translations/ur/LC_MESSAGES/messages.po
  translations/vi/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
  translations/zh_Hant/LC_MESSAGES/messages.po
  website/for_teachers.py
Labels: under-review

#5217 📜 Big clean up level 9 and 10
  content/adventures/ar.yaml
  content/adventures/bg.yaml
  content/adventures/bn.yaml
  content/adventures/ca.yaml
  content/adventures/cs.yaml
  content/adventures/cy.yaml
  content/adventures/da.yaml
  content/adventures/de.yaml
  content/adventures/el.yaml
  content/adventures/en.yaml
  content/adventures/eo.yaml
  content/adventures/es.yaml
  content/adventures/et.yaml
  content/adventures/fa.yaml
  content/adventures/fi.yaml
  content/adventures/fr.yaml
  content/adventures/fy.yaml
  content/adventures/he.yaml
  content/adventures/hi.yaml
  content/adventures/hu.yaml
  content/adventures/ia.yaml
  content/adventures/id.yaml
  content/adventures/it.yaml
  content/adventures/ja.yaml
  content/adventures/kmr.yaml
  content/adventures/ko.yaml
  content/adventures/mi.yaml
  content/adventures/nb_NO.yaml
  content/adventures/nl.yaml
  content/adventures/pa_PK.yaml
  content/adventures/pap.yaml
  content/adventures/pl.yaml
  content/adventures/pt_BR.yaml
  content/adventures/pt_PT.yaml
  content/adventures/ro.yaml
  content/adventures/ru.yaml
  content/adventures/sq.yaml
  content/adventures/sr.yaml
  content/adventures/sv.yaml
  content/adventures/sw.yaml
  content/adventures/te.yaml
  content/adventures/th.yaml
  content/adventures/tl.yaml
  content/adventures/tn.yaml
  content/adventures/tr.yaml
  content/adventures/uk.yaml
  content/adventures/ur.yaml
  content/adventures/vi.yaml
  content/adventures/zh_Hans.yaml
  content/adventures/zh_Hant.yaml
Labels: Weblate-lock

#5220 📜 More music adventures
  content/adventures/ar.yaml
  content/adventures/bg.yaml
  content/adventures/bn.yaml
  content/adventures/ca.yaml
  content/adventures/cs.yaml
  content/adventures/cy.yaml
  content/adventures/da.yaml
  content/adventures/de.yaml
  content/adventures/el.yaml
  content/adventures/en.yaml
  content/adventures/eo.yaml
  content/adventures/es.yaml
  content/adventures/et.yaml
  content/adventures/fa.yaml
  content/adventures/fi.yaml
  content/adventures/fr.yaml
  content/adventures/fy.yaml
  content/adventures/he.yaml
  content/adventures/hi.yaml
  content/adventures/hu.yaml
  content/adventures/ia.yaml
  content/adventures/id.yaml
  content/adventures/it.yaml
  content/adventures/ja.yaml
  content/adventures/kmr.yaml
  content/adventures/ko.yaml
  content/adventures/mi.yaml
  content/adventures/nb_NO.yaml
  content/adventures/nl.yaml
  content/adventures/pa_PK.yaml
  content/adventures/pap.yaml
  content/adventures/pl.yaml
  content/adventures/pt_BR.yaml
  content/adventures/pt_PT.yaml
  content/adventures/ro.yaml
  content/adventures/ru.yaml
  content/adventures/sq.yaml
  content/adventures/sr.yaml
  content/adventures/sv.yaml
  content/adventures/sw.yaml
  content/adventures/te.yaml
  content/adventures/th.yaml
  content/adventures/tl.yaml
  content/adventures/tn.yaml
  content/adventures/tr.yaml
  content/adventures/uk.yaml
  content/adventures/ur.yaml
  content/adventures/vi.yaml
  content/adventures/zh_Hans.yaml
  content/adventures/zh_Hant.yaml
Labels: Weblate-lock

#5200 💻 Front page start learning/teaching
  app.py
  content/adventures/cs.yaml
  content/adventures/da.yaml
  content/adventures/fr.yaml
  messages.pot
  templates/main-page.html
  tests/cypress/e2e/home_page/buttons/try_it_button.cy.js
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/ca/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/cy/LC_MESSAGES/messages.po
  translations/da/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fi/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/ia/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/kmr/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/mi/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pa_PK/LC_MESSAGES/messages.po
  translations/pap/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ro/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sq/LC_MESSAGES/messages.po
  translations/sr/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/te/LC_MESSAGES/messages.po
  translations/th/LC_MESSAGES/messages.po
  translations/tl/LC_MESSAGES/messages.po
  translations/tn/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/uk/LC_MESSAGES/messages.po
  translations/ur/LC_MESSAGES/messages.po
  translations/vi/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
  translations/zh_Hant/LC_MESSAGES/messages.po
Labels: under-review

#5258 🪲 fix feedback modal
  templates/layout.html
Labels: under-review

#5264 📜 Cleaning up level 12 up and also adds new adventure in level 16
  content/adventures/ar.yaml
  content/adventures/bg.yaml
  content/adventures/bn.yaml
  content/adventures/ca.yaml
  content/adventures/cs.yaml
  content/adventures/cy.yaml
  content/adventures/da.yaml
  content/adventures/de.yaml
  content/adventures/el.yaml
  content/adventures/en.yaml
  content/adventures/eo.yaml
  content/adventures/es.yaml
  content/adventures/et.yaml
  content/adventures/fa.yaml
  content/adventures/fi.yaml
  content/adventures/fr.yaml
  content/adventures/fy.yaml
  content/adventures/he.yaml
  content/adventures/hi.yaml
  content/adventures/hu.yaml
  content/adventures/ia.yaml
  content/adventures/id.yaml
  content/adventures/it.yaml
  content/adventures/ja.yaml
  content/adventures/kmr.yaml
  content/adventures/ko.yaml
  content/adventures/mi.yaml
  content/adventures/nb_NO.yaml
  content/adventures/nl.yaml
  content/adventures/pa_PK.yaml
  content/adventures/pap.yaml
  content/adventures/pl.yaml
  content/adventures/pt_BR.yaml
  content/adventures/pt_PT.yaml
  content/adventures/ro.yaml
  content/adventures/ru.yaml
  content/adventures/sq.yaml
  content/adventures/sr.yaml
  content/adventures/sv.yaml
  content/adventures/sw.yaml
  content/adventures/te.yaml
  content/adventures/th.yaml
  content/adventures/tl.yaml
  content/adventures/tn.yaml
  content/adventures/tr.yaml
  content/adventures/uk.yaml
  content/adventures/ur.yaml
  content/adventures/vi.yaml
  content/adventures/zh_Hans.yaml
  content/adventures/zh_Hant.yaml
  hedy_content.py
Labels: Weblate-lock

#5259 🧹 Address TODOs in hedy.py
  hedy.py
  tests/test_distance_algo.py
Labels: under-review

#5288 📜Fixed typos
  content/adventures/ar.yaml
  content/adventures/bg.yaml
  content/adventures/bn.yaml
  content/adventures/ca.yaml
  content/adventures/cs.yaml
  content/adventures/cy.yaml
  content/adventures/da.yaml
  content/adventures/de.yaml
  content/adventures/el.yaml
  content/adventures/en.yaml
  content/adventures/eo.yaml
  content/adventures/es.yaml
  content/adventures/et.yaml
  content/adventures/fa.yaml
  content/adventures/fi.yaml
  content/adventures/fr.yaml
  content/adventures/fy.yaml
  content/adventures/he.yaml
  content/adventures/hi.yaml
  content/adventures/hu.yaml
  content/adventures/ia.yaml
  content/adventures/id.yaml
  content/adventures/it.yaml
  content/adventures/ja.yaml
  content/adventures/kmr.yaml
  content/adventures/ko.yaml
  content/adventures/mi.yaml
  content/adventures/nb_NO.yaml
  content/adventures/pa_PK.yaml
  content/adventures/pap.yaml
  content/adventures/pl.yaml
  content/adventures/pt_BR.yaml
  content/adventures/pt_PT.yaml
  content/adventures/ro.yaml
  content/adventures/ru.yaml
  content/adventures/sq.yaml
  content/adventures/sr.yaml
  content/adventures/sv.yaml
  content/adventures/sw.yaml
  content/adventures/te.yaml
  content/adventures/th.yaml
  content/adventures/tl.yaml
  content/adventures/tn.yaml
  content/adventures/tr.yaml
  content/adventures/uk.yaml
  content/adventures/ur.yaml
  content/adventures/vi.yaml
  content/adventures/zh_Hant.yaml
Labels: Weblate-lock

#5283 🖊️ Add new indent error messages for level 8
  content/error-messages.txt
  exceptions.py
  hedy.py
  messages.pot
  tests/Tester.py
  tests/test_level/test_level_08.py
  tests/test_level/test_level_09.py
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/ca/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/cy/LC_MESSAGES/messages.po
  translations/da/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fi/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/ia/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/kmr/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/mi/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pa_PK/LC_MESSAGES/messages.po
  translations/pap/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ro/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sq/LC_MESSAGES/messages.po
  translations/sr/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/te/LC_MESSAGES/messages.po
  translations/th/LC_MESSAGES/messages.po
  translations/tl/LC_MESSAGES/messages.po
  translations/tn/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/uk/LC_MESSAGES/messages.po
  translations/ur/LC_MESSAGES/messages.po
  translations/vi/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
  translations/zh_Hant/LC_MESSAGES/messages.po
Labels: under-review

#5292 🪲 Check if classes and levels exist in adv
  website/for_teachers.py
Labels: under-review

#5335 Translations from Hosted Weblate
  content/achievements/pt_PT.yaml
  content/adventures/sl.yaml
  content/adventures/zh_Hans.yaml
  content/quizzes/zh_Hans.yaml
  content/slides/zh_Hans.yaml
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: translations
