Repository hedyorg/hedy, pull requests merged in 2024-04, with the labels that each got.

#5346 Resolve Weblate merge conflicts
  content/quizzes/en.yaml
  content/quizzes/fr.yaml
  content/quizzes/zh_Hans.yaml
  translations/zh_Hans/LC_MESSAGES/messages.po
Labels: translations

#5326 💻 format all old adventure contents with curlies
  website/frontend_types.py
  website/public_adventures.py
Labels: under-review

#5345 🧹 Reduce duplication in snippet testing
  tests/Tester.py
  tests/test_snippets/snippet_tester.py
  tests/test_snippets/test_adventures.py
  tests/test_snippets/test_cheatsheets.py
  tests/test_snippets/test_parsons.py
  tests/test_snippets/test_slides.py
Labels: under-review

#5421 🧪 Test a few broken programs from the front-end
  tests/cypress/e2e/hedy_page/invalid_program.cy.js
Labels: under-review

#5393 🧹 Refactor cypress tests (part 1)
  templates/admin/admin-achievements.html
  templates/admin/admin-adventures.html
  templates/admin/admin-users.html
  templates/explore.html
  templates/layout.html
  tests/cypress/e2e/admin_page/achievements_page/return_to_admin_page_button.cy.js
  tests/cypress/e2e/admin_page/adventures_page/return_to_admin_page_button.cy.js
  tests/cypress/e2e/admin_page/adventures_page/view_adventure_button.cy.js
  tests/cypress/e2e/admin_page/user_overview/return_to_admin_page.cy.js
  tests/cypress/e2e/admin_page/user_overview/view_all_users.cy.js
  tests/cypress/e2e/admin_page/user_overview/visible_attributes_checkboxes.cy.js
  tests/cypress/e2e/explore_programs_page/explore_programs.cy.js
  tests/cypress/e2e/feedback/feedback_modal.cy.js
  tests/cypress/e2e/for-teacher_page/class_page/add_student_invite_by_username.cy.js
  tests/cypress/e2e/for-teacher_page/customize-adventure_page/remove_button.cy.js
  tests/cypress/e2e/for-teacher_page/general/click_duplicate_class.cy.js
  tests/cypress/e2e/for-teacher_page/general/duplicate_class.cy.js
  tests/cypress/e2e/public_programs/programs_page.cy.js
  tests/cypress/e2e/signup_page/create_account_button.cy.js
  tests/cypress/e2e/tools/adventures/adventure.js
  tests/cypress/e2e/tools/classes/class.js
Labels: under-review

#5435 📜 Adds more debugging slides
  content/slides/ar.yaml
  content/slides/bg.yaml
  content/slides/bn.yaml
  content/slides/ca.yaml
  content/slides/cs.yaml
  content/slides/cy.yaml
  content/slides/da.yaml
  content/slides/de.yaml
  content/slides/el.yaml
  content/slides/en.yaml
  content/slides/eo.yaml
  content/slides/es.yaml
  content/slides/et.yaml
  content/slides/fa.yaml
  content/slides/fi.yaml
  content/slides/fr.yaml
  content/slides/fy.yaml
  content/slides/he.yaml
  content/slides/hi.yaml
  content/slides/hu.yaml
  content/slides/ia.yaml
  content/slides/id.yaml
  content/slides/it.yaml
  content/slides/ja.yaml
  content/slides/kmr.yaml
  content/slides/ko.yaml
  content/slides/mi.yaml
  content/slides/nb_NO.yaml
  content/slides/nl.yaml
  content/slides/pa_PK.yaml
  content/slides/pap.yaml
  content/slides/pl.yaml
  content/slides/pt_BR.yaml
  content/slides/pt_PT.yaml
  content/slides/ro.yaml
  content/slides/ru.yaml
  content/slides/sl.yaml
  content/slides/sq.yaml
  content/slides/sr.yaml
  content/slides/sv.yaml
  content/slides/sw.yaml
  content/slides/te.yaml
  content/slides/th.yaml
  content/slides/tl.yaml
  content/slides/tn.yaml
  content/slides/tr.yaml
  content/slides/uk.yaml
  content/slides/ur.yaml
  content/slides/vi.yaml
  content/slides/zh_Hans.yaml
  content/slides/zh_Hant.yaml
Labels: Weblate-lock

#5409 🪲 Exclude end blocks from comments
  grammars/level5-Additions.lark
  grammars/terminals.lark
  tests/test_level/test_level_09.py
  tests/test_level/test_level_12.py
  tests/test_level/test_level_18.py
Labels: under-review

#5434 📜 Adds Snowflake drawing adventure
  content/adventures/ar.yaml
  content/adventures/bg.yaml
  content/adventures/bn.yaml
  content/adventures/ca.yaml
  content/adventures/cs.yaml
  content/adventures/cy.yaml
  content/adventures/da.yaml
  content/adventures/de.yaml
  content/adventures/el.yaml
  content/adventures/en.yaml
  content/adventures/eo.yaml
  content/adventures/es.yaml
  content/adventures/et.yaml
  content/adventures/fa.yaml
  content/adventures/fi.yaml
  content/adventures/fr.yaml
  content/adventures/fy.yaml
  content/adventures/he.yaml
  content/adventures/hi.yaml
  content/adventures/hu.yaml
  content/adventures/ia.yaml
  content/adventures/id.yaml
  content/adventures/it.yaml
  content/adventures/ja.yaml
  content/adventures/kmr.yaml
  content/adventures/ko.yaml
  content/adventures/mi.yaml
  content/adventures/nb_NO.yaml
  content/adventures/nl.yaml
  content/adventures/pa_PK.yaml
  content/adventures/pap.yaml
  content/adventures/pl.yaml
  content/adventures/pt_BR.yaml
  content/adventures/pt_PT.yaml
  content/adventures/ro.yaml
  content/adventures/ru.yaml
  content/adventures/sl.yaml
  content/adventures/sq.yaml
  content/adventures/sr.yaml
  content/adventures/sv.yaml
  content/adventures/sw.yaml
  content/adventures/te.yaml
  content/adventures/th.yaml
  content/adventures/tl.yaml
  content/adventures/tn.yaml
  content/adventures/tr.yaml
  content/adventures/uk.yaml
  content/adventures/ur.yaml
  content/adventures/vi.yaml
  content/adventures/zh_Hans.yaml
  content/adventures/zh_Hant.yaml
Labels: Weblate-lock

#5470 📜 Rephrasing level 2 is command adventure
  content/adventures/ar.yaml
  content/adventures/bg.yaml
  content/adventures/bn.yaml
  content/adventures/ca.yaml
  content/adventures/cs.yaml
  content/adventures/cy.yaml
  content/adventures/da.yaml
  content/adventures/de.yaml
  content/adventures/el.yaml
  content/adventures/en.yaml
  content/adventures/eo.yaml
  content/adventures/es.yaml
  content/adventures/et.yaml
  content/adventures/fa.yaml
  content/adventures/fi.yaml
  content/adventures/fr.yaml
  content/adventures/fy.yaml
  content/adventures/he.yaml
  content/adventures/hi.yaml
  content/adventures/hu.yaml
  content/adventures/ia.yaml
  content/adventures/id.yaml
  content/adventures/it.yaml
  content/adventures/ja.yaml
  content/adventures/kmr.yaml
  content/adventures/ko.yaml
  content/adventures/mi.yaml
  content/adventures/nb_NO.yaml
  content/adventures/pa_PK.yaml
  content/adventures/pap.yaml
  content/adventures/pl.yaml
  content/adventures/pt_BR.yaml
  content/adventures/pt_PT.yaml
  content/adventures/ro.yaml
  content/adventures/ru.yaml
  content/adventures/sq.yaml
  content/adventures/sr.yaml
  content/adventures/sv.yaml
  content/adventures/sw.yaml
  content/adventures/te.yaml
  content/adventures/th.yaml
  content/adventures/tl.yaml
  content/adventures/tn.yaml
  content/adventures/uk.yaml
  content/adventures/ur.yaml
  content/adventures/vi.yaml
  content/adventures/zh_Hant.yaml
Labels: Weblate-lock

#5490 Resolve Weblate conflicts
  content/adventures/nl.yaml
  content/quizzes/iba.yaml
Labels: translations

#5467 💻 Guest teacher connect option in teacher signup
  messages.pot
  templates/signup.html
  tests/cypress/e2e/signup_page/connect_guest_teacher_create_account.cy.js
  translations/ar/LC_MESSAGES/messages.po
  translations/bg/LC_MESSAGES/messages.po
  translations/bn/LC_MESSAGES/messages.po
  translations/ca/LC_MESSAGES/messages.po
  translations/cs/LC_MESSAGES/messages.po
  translations/cy/LC_MESSAGES/messages.po
  translations/da/LC_MESSAGES/messages.po
  translations/de/LC_MESSAGES/messages.po
  translations/el/LC_MESSAGES/messages.po
  translations/en/LC_MESSAGES/messages.po
  translations/eo/LC_MESSAGES/messages.po
  translations/es/LC_MESSAGES/messages.po
  translations/et/LC_MESSAGES/messages.po
  translations/fa/LC_MESSAGES/messages.po
  translations/fi/LC_MESSAGES/messages.po
  translations/fr/LC_MESSAGES/messages.po
  translations/fy/LC_MESSAGES/messages.po
  translations/he/LC_MESSAGES/messages.po
  translations/hi/LC_MESSAGES/messages.po
  translations/hu/LC_MESSAGES/messages.po
  translations/ia/LC_MESSAGES/messages.po
  translations/iba/LC_MESSAGES/messages.po
  translations/id/LC_MESSAGES/messages.po
  translations/it/LC_MESSAGES/messages.po
  translations/ja/LC_MESSAGES/messages.po
  translations/kmr/LC_MESSAGES/messages.po
  translations/ko/LC_MESSAGES/messages.po
  translations/mi/LC_MESSAGES/messages.po
  translations/ms/LC_MESSAGES/messages.po
  translations/nb_NO/LC_MESSAGES/messages.po
  translations/nl/LC_MESSAGES/messages.po
  translations/pa_PK/LC_MESSAGES/messages.po
  translations/pap/LC_MESSAGES/messages.po
  translations/pl/LC_MESSAGES/messages.po
  translations/pt_BR/LC_MESSAGES/messages.po
  translations/pt_PT/LC_MESSAGES/messages.po
  translations/ro/LC_MESSAGES/messages.po
  translations/ru/LC_MESSAGES/messages.po
  translations/sl/LC_MESSAGES/messages.po
  translations/sq/LC_MESSAGES/messages.po
  translations/sr/LC_MESSAGES/messages.po
  translations/sv/LC_MESSAGES/messages.po
  translations/sw/LC_MESSAGES/messages.po
  translations/te/LC_MESSAGES/messages.po
  translations/th/LC_MESSAGES/messages.po
  translations/tl/LC_MESSAGES/messages.po
  translations/tn/LC_MESSAGES/messages.po
  translations/tr/LC_MESSAGES/messages.po
  translations/uk/LC_MESSAGES/messages.po
  translations/ur/LC_MESSAGES/messages.po
  translations/vi/LC_MESSAGES/messages.po
  translations/zh_Hans/LC_MESSAGES/messages.po
  translations/zh_Hant/LC_MESSAGES/messages.po
  website/auth_pages.py
Labels: under-review
